export const FETCH_BLOCK_INFO_BEGIN = 'FETCH_BLOCK_INFO_BEGIN';
export const FETCH_BLOCK_INFO_SUCCESS = 'FETCH_BLOCK_INFO_SUCCESS';
export const FETCH_BLOCK_INFO_FAILURE = 'FETCH_BLOCK_INFO_FAILURE';
